FROM php:8.3.2-fpm

# Assume that the composer install command is run locally before running the container.

WORKDIR /var/www

RUN apt-get update \
    && apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql

COPY . .

